package main

type Lang struct {
	Code string
	Name string
}

// list of languages that we know about
var (
	Languages = [...]Lang{
		Lang{"en", "English"},
		Lang{"am", "Armenian"},
		Lang{"af", "Afrikaans"},
		Lang{"pt", "Portuguese"},
		Lang{"br", "Portuguese Brazilian"},
		Lang{"bg", "Bulgarian"},
		Lang{"de", "German"},
		Lang{"tr", "Turkish"},
		Lang{"by", "Belarusian"},
		Lang{"hu", "Hungarian"},
		Lang{"lt", "Lithuanian"},
		Lang{"my", "Malay"},
		Lang{"ja", "Japanese"},
		Lang{"fa", "Farsi"},
		Lang{"it", "Italian"},
		Lang{"nl", "Dutch"},
		Lang{"fi", "Finnish"},
		Lang{"ca", "Catalan"},
		Lang{"ca-xv", "Catalan Valencian"},
		Lang{"sl", "Slovenian"},
		Lang{"sr-rs", "Serbian Cyrillic"},
		Lang{"ml", "Malayalam"},
		Lang{"he", "Hebrew"},
		Lang{"sp-rs", "Serbian Latin"},
		Lang{"id", "Indonesian"},
		Lang{"mk", "Macedonian"},
		Lang{"ro", "Romanian"},
		Lang{"sk", "Slovak"},
		Lang{"vn", "Vietnamese"},
		Lang{"kr", "Korean"},
		Lang{"bn", "Bengali"},
		Lang{"cn", "Chinese Simplified"},
		Lang{"fr", "French"},
		Lang{"ru", "Russian"},
		Lang{"gl", "Galician"},
		Lang{"es", "Spanish"},
		Lang{"ar", "Arabic"},
		Lang{"uk", "Ukrainian"},
		Lang{"eu", "Basque"},
		Lang{"gr", "Greek"},
		Lang{"hr", "Croatian"},
		Lang{"tl", "Filipino"},
		Lang{"sn", "Shona"},
		Lang{"tw", "Chinese Traditional"},
		Lang{"cy", "Welsh"},
		Lang{"ga", "Irish"},
		Lang{"mm", "Burmese"},
		Lang{"pa", "Punjabi"},
		Lang{"hi", "Hindi"},
		Lang{"nn", "Norwegian"},
		Lang{"sv", "Swedish"},
		Lang{"pl", "Polish"},
		Lang{"dk", "Danish"},
		Lang{"ta", "Tamil"},
		Lang{"cz", "Czech"},
		Lang{"th", "Thai"},
		Lang{"no", "Norwegian"},
		Lang{"kw", "Cornish"},
		Lang{"fy-nl", "Frisian"},
		Lang{"si", "Sinhalese"},
		Lang{"bs", "Bosnian"},
		Lang{"ka", "Georgian"},
		Lang{"et", "Estonian"},
		Lang{"uz", "Uzbek"}}
)
